### PR TITLE
Use accessors to prevent private access errors when an older version of lodestone api is installed

### LINKED ISSUE #3: When the game tries to load a planet/star it crashes maybe it is a mod conflict. Any help, please?
[14:33:04] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at net.minecraft.class_918.method_4026(class_918.java:360) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_36543(class_918.java:340) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_27951(class_918.java:336) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_329.method_1762(class_329.java:1257) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_329.method_1759(class_329.java:579) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_329.method_1753(class_329.java:204) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:862) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [minecraft-1.19.2.i0:0/:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [minecraft-1.19.2.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [minecraft-1.19.2.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) [quilt-loader-0.22.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.22.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.22.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalAccessError: class doctor4t.astronomical.client.render.world.AstraWorldVFXBuilder tried to access field com.sammy.lodestone.systems.rendering.VFXBuilders$WorldVFXBuilder.r (doctor4t.astronomical.client.render.world.AstraWorldVFXBuilder and com.sammy.lodestone.systems.rendering.VFXBuilders$WorldVFXBuilder are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @5bcab519)
	at doctor4t.astronomical.client.render.world.AstraWorldVFXBuilder.renderSphere(AstraWorldVFXBuilder.java:184) ~[astronomical-1.0.01.19.2.i0:0/:?]
	at doctor4t.astronomical.client.AstronomicalClient.renderAstralObject(AstronomicalClient.java:84) ~[astronomical-1.0.01.19.2.i0:0/:?]
	at net.minecraft.class_918.handler$emf000$astronomical$renderItem(class_918.java:4572) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_23179(class_918.java) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_4021(class_918.java:307) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_918.method_4026(class_918.java:350) ~[minecraft-1.19.2.i0:0/:?]

### PR DESCRIPTION
**Pull request by JustRed23**
Fixes #3 and #7

### CODE REVIEW

**Comment by JustRed23** [comment]
For more insight, lodestone api versions older than **e4925a6faf** has some values that have private access, this would cause a conflict when other ladysnake mods are installed that contain older versions of this api mod

**Comment by XsyncanumX** [comment]
> For more insight, lodestone api versions older than **e4925a6faf** has some values that have private access, this would cause a conflict when other ladysnake mods are installed that contain older versions of this api mod

I do not use lodestone api- perhaps that might be causing some problems? Other than that, you're basically speaking another language to me, I do not understand most of what you've said other than 'lodestone api might be causing problems'. Also, I'm new to using github so apologies if this is a weird way to do a reply.

**Comment by JustRed23** [comment]
Lodestone actually is being used here, AstraWorldVFXBuilder extends VFXBuilders.WorldVFXBuilder which is a part of the lodestone api

**Comment by JustRed23** [comment]
also lodestone is bundled with the mod, if you open the mod with winrar or some unzipping tool youll see that it is bundled

**Comment by XsyncanumX** [comment]
oh, I see. thank you for the clarification about lodestone.

**Comment by UpcraftLP** [comment]
I think the actual solution here is to get a new release of lodestonelib going (CC @Arathain) and then bump the dependency version, so quilt loader doesn't sort the newer version lower than the older version.

**Comment by JustRed23** [comment]
That is the problem, people do not update their mods regularily, so mods with lodestone bundled will still cause problems as they are out of date

**Comment by JustRed23** [comment]
This is just a quick fix for those out of date mods

**Comment by UpcraftLP** [comment]
> That is the problem, people do not update their mods regularily, so mods with lodestone bundled will still cause problems as they are out of date

no they will not, because quilt loader only ever loads the "latest" version of dependencies that are provided as jar-in-jar.

The current issue stems from using a git commit hash as version, which loader has no way of knowing how to sort other than via string comparison, leading to unpredictable ordering.

This can be solved if lodestone releases a proper tagged version for this mod to depend on, as loader will sort those higher than commit hash versions.

**Comment by JustRed23** [comment]
I see

**Pull request closed without merging**
